function makefig_topo(plot_topo, chanlocs, plotchans)

topoplot(plot_topo, chanlocs, 'electrodes', 'on', ...
    'maplimits', 'absmax', ...
    'conv', 'on', ...
    'emarker2', {plotchans,'.','w',15,1} ,...
    'whitebk','on');
colorbar('eastoutside')
